import type { ModuleId, TopicPack } from './types';

export const topics: TopicPack[] = [
  { id:'social-media', title:'Social media age limit', question:'Should social media platforms have a strict minimum age of sixteen?', basicSubject:'social media platforms', preciseSubject:'platforms built around endless scrolling and recommendation algorithms', predicate:'should have a strict minimum age of sixteen', stance:'I strongly believe that', hedge:'in most cases', reason:'because younger teenagers are especially vulnerable to social pressure and addictive design', consequence:'which can gradually damage their confidence, concentration, and sleep', example:'For example, a thirteen-year-old who constantly compares their life with influencers may start seeing ordinary life as inadequate.', concession:'Although social media can help young people communicate and learn', counterargument:'Some people argue that parents should manage the risk themselves.', rebuttal:'However, this ignores how difficult recommendation systems are to understand and control.', conclusion:'For these reasons, a strict age limit would be a reasonable form of protection.' },
  { id:'ai-authorship', title:'AI and artistic authorship', question:'If an AI writes code or generates symphonic metal music, who is the real artist?', basicSubject:'the person using the AI', preciseSubject:'the person who defines the concept, selects the outputs, and makes the final creative decisions', predicate:'should still be considered the main artist', stance:'My view is that', hedge:'in most cases', reason:'because creative direction involves intention and judgment, not only manual execution', consequence:'which means that the tool does not automatically replace human authorship', example:'For example, a musician may generate twenty melodies with AI but still choose, edit, arrange, and combine them into a coherent song.', concession:'Although the AI may produce most of the raw material', counterargument:'Some people argue that the machine deserves equal credit because it created the actual notes or code.', rebuttal:'However, this overlooks the human decisions that define the purpose, style, and final result.', conclusion:'Ultimately, authorship should depend on meaningful creative control rather than on who performed every individual step.' },
  { id:'memories', title:'Deleting painful memories', question:'Should people be allowed to delete their most painful memories?', basicSubject:'people', preciseSubject:'adults suffering from severe and clinically diagnosed trauma', predicate:'should be allowed to delete painful memories', stance:'I would argue that', hedge:'only in exceptional cases', reason:'because some memories can remain psychologically destructive for years', consequence:'which may prevent a person from functioning normally even after therapy', example:'For example, someone who survived a violent attack might continue experiencing panic whenever they enter a similar environment.', concession:'Although painful experiences can teach important lessons and shape personal identity', counterargument:'Some people argue that removing any memory would fundamentally change who a person is.', rebuttal:'That concern is valid, but it does not mean that every form of treatment should be rejected.', conclusion:'For that reason, memory editing should be treated as a medical last resort rather than as an ordinary lifestyle choice.' },
  { id:'virtual-world', title:'A perfect virtual world', question:'Could living in a perfect virtual world ever be better than living in reality?', basicSubject:"living in a perfect virtual world", preciseSubject:"spending most of one's life inside a realistic, personalized virtual environment", predicate:'could eventually become more attractive than ordinary reality', stance:'To be completely honest, I think that', hedge:'for many people', reason:'because virtual life could remove physical limitations, financial barriers, and social rejection', consequence:'which could make real life feel unnecessarily difficult and disappointing', example:'For example, a lonely person could instantly enter a world where they have friends, status, and complete control over their surroundings.', concession:'Even though virtual environments could provide comfort, education, and new experiences', counterargument:'Some people might say that happiness is happiness, regardless of whether it comes from the physical world.', rebuttal:'The problem is that a life without genuine risk, limitation, or uncertainty may gradually lose meaning.', conclusion:'Overall, virtual worlds could improve life, but they should complement reality rather than replace it.' },
  { id:'offline', title:'Forty-eight hours offline', question:'Could most people survive forty-eight hours without a smartphone, the internet, or AI?', basicSubject:'most people', preciseSubject:'people who depend on their phones for communication, navigation, entertainment, and work', predicate:'would struggle to spend forty-eight hours completely offline', stance:'I am convinced that', hedge:'at least at first', reason:'because smartphones have absorbed dozens of everyday habits into a single device', consequence:'which makes even simple activities feel inconvenient without them', example:'For example, many people no longer memorize phone numbers, carry maps, plan routes in advance, or keep physical tickets.', concession:'Although a short digital break could reduce stress and improve attention', counterargument:'Some people insist that disconnecting is easy because smartphones are only tools.', rebuttal:'However, a tool becomes difficult to abandon when everyday life has been designed around it.', conclusion:'At the end of the day, surviving would be easy, but functioning normally would be surprisingly difficult.' },
  { id:'fitness', title:'Fitness as mental therapy', question:'Is hard physical training mainly about appearance, or can it be a form of mental therapy?', basicSubject:'hard physical training', preciseSubject:'consistent strength, conditioning, and core training', predicate:'can be a form of mental therapy as much as physical exercise', stance:'From my perspective,', hedge:'for many people', reason:'because it creates a clear challenge that demands full attention', consequence:'which can temporarily silence stress, overthinking, and everyday frustration', example:'For example, during a difficult workout, a person is usually focused on breathing, technique, and finishing the next repetition rather than on external problems.', concession:'Although appearance and physical performance are obvious motivations', counterargument:'Some people argue that exercise cannot be called therapy because it does not solve the original problem.', rebuttal:'That is true, but an activity does not need to solve every problem in order to improve emotional stability.', conclusion:'For these reasons, training can be both physical maintenance and a powerful mental reset.' },
  { id:'pineapple', title:'Pineapple on pizza', question:'Is there any universe where pineapple on pizza is acceptable?', basicSubject:'pineapple on pizza', preciseSubject:'the combination of sweet pineapple, salty cheese, and a savory tomato base', predicate:'is acceptable when the flavors are balanced', stance:'Against my better judgment, I admit that', hedge:'occasionally', reason:'because contrast between sweet and salty ingredients can work surprisingly well', consequence:'which is the same principle used in many respected dishes', example:'For example, people regularly combine fruit with cheese, cured meat, or spicy sauces without treating it as a culinary crime.', concession:'Although badly made pineapple pizza can be aggressively unpleasant', counterargument:'Traditionalists argue that fruit has no place on a serious pizza.', rebuttal:'However, tradition is not a scientific law, and Italian cuisine itself has always evolved through regional experimentation.', conclusion:'So, while it should never be compulsory, pineapple pizza deserves legal protection from total annihilation.' },
  { id:'mars', title:'Colonizing Mars', question:'Would you join the first permanent colony on Mars if there were no guaranteed return journey?', basicSubject:'the first human colony on Mars', preciseSubject:'a permanent settlement with no guaranteed return journey to Earth', predicate:'should initially be limited to trained volunteers', stance:'I firmly believe that', hedge:'under current conditions', reason:'because the psychological and physical risks would be extreme', consequence:'which would make ordinary consent far more complicated than it appears', example:'For example, colonists might face isolation, radiation exposure, medical emergencies, and years without direct contact with their families.', concession:"Although a Mars colony could become one of humanity's greatest achievements", counterargument:'Some people argue that major exploration has always required individuals willing to accept extraordinary danger.', rebuttal:'That is true, but volunteers must understand that this would not be a temporary expedition with a reliable rescue plan.', conclusion:'For these reasons, participation should be voluntary, highly selective, and based on complete transparency about the risks.' },
  { id:'animals', title:'If animals could speak', question:'If animals could speak, would humanity stop eating meat?', basicSubject:'human eating habits', preciseSubject:'the way humans raise, kill, and consume animals', predicate:'would change dramatically if animals could speak', stance:'I strongly suspect that', hedge:'within a few years', reason:'because emotional communication would make it much harder to treat animals as anonymous products', consequence:'which could turn an abstract ethical issue into a personal relationship', example:'For example, many people would struggle to eat an animal that had previously expressed fear, affection, or a clear desire to live.', concession:'Although some people would continue eating meat for cultural, nutritional, or practical reasons', counterargument:'Others might argue that intelligence and language should not determine whether an animal can be eaten.', rebuttal:'That objection is reasonable, but direct communication would still make the moral cost impossible to ignore.', conclusion:'Ultimately, speaking animals would not end meat consumption immediately, but they would completely transform the debate.' },
  { id:'remote-work', title:'Remote life and isolation', question:'Is full remote work slowly making people more antisocial?', basicSubject:'full remote work', preciseSubject:'working from home without regular face-to-face contact with colleagues', predicate:'can gradually make some people more socially isolated', stance:'I believe that', hedge:'in certain situations', reason:'because casual conversations and spontaneous interactions disappear from the working day', consequence:"which can reduce a person's overall exposure to other people", example:'For example, someone who lives alone may finish an entire week with almost no meaningful in-person interaction.', concession:'Although remote work offers freedom, comfort, and valuable flexibility', counterargument:'Some people argue that social life should come from friends and family rather than from the workplace.', rebuttal:"That is fair, but work still provides regular contact for people whose private social network is small.", conclusion:'Therefore, remote work is not inherently antisocial, but it needs deliberate social habits to remain healthy.' }
];

export const moduleOrder: ModuleId[] = ['stance','precision','hedge','reason','consequence','example','contrast','counterargument','rebuttal','conclusion'];
export const metadata: Record<ModuleId, { name:string; category:string; level:string; weight:number; explanation:string; feedback:string; grammar:string; followUp:string; correction:string }> = {
  stance:{name:'Strong stance',category:'Clarify the opinion',level:'A2',weight:1,explanation:'Rende la posizione più chiara e decisa.',feedback:'Your opinion is now more explicit. The listener immediately understands your position.',grammar:'stance phrase + that + clause',followUp:'How strongly do you hold this view?',correction:'Choose a stance phrase that matches your certainty.'},
  precision:{name:'Precision',category:'Clarify the opinion',level:'B1',weight:2,explanation:'Sostituisce parole generiche con un soggetto più specifico.',feedback:'The broad subject has been replaced with a more specific one.',grammar:'expanded noun phrase + defining detail',followUp:'Which exact people or things do you mean?',correction:'Replace one vague word with a more precise expression.'},
  hedge:{name:'Hedge',category:'Clarify the opinion',level:'B1',weight:2,explanation:"Aggiunge cautela e impedisce che l'opinione sembri assoluta.",feedback:'The claim is now more nuanced and less absolute.',grammar:'qualifying phrase + comma + clause',followUp:'Are there any exceptions?',correction:'Make an absolute claim more cautious.'},
  reason:{name:'Main reason',category:'Develop the logic',level:'B1',weight:2,explanation:"Spiega la causa principale dell'opinione.",feedback:'The answer now explains why the speaker holds this position.',grammar:'main clause + because + subject + verb',followUp:'Why is that consequence important?',correction:'Replace one vague word with a more precise expression.'},
  consequence:{name:'Consequence',category:'Develop the logic',level:'B1/B2',weight:2,explanation:'Mostra cosa può accadere come risultato.',feedback:'The idea has been developed through cause and effect.',grammar:'complete clause, which can/may + verb',followUp:'What could happen over time?',correction:'Connect two short sentences using “which”.'},
  example:{name:'Concrete example',category:'Support the argument',level:'B1',weight:2,explanation:"Collega l'idea a una situazione concreta.",feedback:'The argument is now supported by a concrete situation.',grammar:'For example, + specific situation',followUp:'Can you make this example more specific?',correction:'Add a person, place, or realistic detail.'},
  contrast:{name:'Contrast',category:'Add complexity',level:'B2',weight:3,explanation:'Riconosce un vantaggio o un punto di vista opposto.',feedback:'The answer now recognizes that the issue has more than one side.',grammar:'Although + clause, main clause',followUp:'What is the strongest argument against your position?',correction:'Combine the two ideas without using “but”.'},
  counterargument:{name:'Counterargument',category:'Add complexity',level:'B2',weight:3,explanation:"Presenta chiaramente l'obiezione dell'altra parte.",feedback:'The opposing position is now represented fairly.',grammar:'Some people argue that + clause',followUp:'Why might a reasonable person disagree?',correction:'Present the objection without emotional language.'},
  rebuttal:{name:'Rebuttal',category:'Add complexity',level:'B2/C1',weight:3,explanation:"Risponde all'obiezione senza ignorarla.",feedback:'The speaker now answers the opposing position instead of merely mentioning it.',grammar:'linking phrase + response clause',followUp:'Which part of the objection is weakest?',correction:'Acknowledge one valid point before responding.'},
  conclusion:{name:'Conclusion',category:'Complete the response',level:'A2/B1',weight:1,explanation:'Chiude il ragionamento tornando alla posizione principale.',feedback:'The argument now has a clear final destination.',grammar:'concluding linker + final position',followUp:'What should the listener remember?',correction:'Avoid introducing a new idea in the conclusion.'}
};

export const challenges = [
  {name:'Three-piece B1',description:'Reach B1 using no more than three modules.',test:(a:ModuleId[],p:number)=>p>=6&&a.length<=3},
  {name:'Evidence-free B2',description:'Reach B2 without using an example.',test:(a:ModuleId[],p:number)=>p>=10&&!a.includes('example')},
  {name:'Logic chain',description:'Add precision, a reason, and a consequence.',test:(a:ModuleId[])=>['precision','reason','consequence'].every(x=>a.includes(x as ModuleId))},
  {name:'Debate ready',description:'Build an argument with a counterargument and rebuttal.',test:(a:ModuleId[])=>a.includes('counterargument')&&a.includes('rebuttal')},
  {name:'Compact C1',description:'Reach C1 with no more than eight modules.',test:(a:ModuleId[],p:number)=>p>=16&&a.length<=8},
  {name:'Add nuance',description:'Use a hedge and a contrast without changing the main position.',test:(a:ModuleId[])=>a.includes('hedge')&&a.includes('contrast')},
  {name:'60-second answer',description:'Build an answer of at least 100 words.',test:(_a:ModuleId[],_p:number,w:number)=>w>=100}
];
